baseURL = 'https://amohammadzadeh.github.io/'
languageCode = 'en-us'
title = 'AMDev'
theme = 'hugo-PaperMod'
math = true

[params]
env = "production"
    author = "Ahmad M."
    defaultTheme = "auto"
    ShowShareButtons = true
    ShowReadingTime = true
    displayFullLangName = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    ShowRssButtonInSectionTermList = true
    ShowAllPagesInArchive = true
    ShowPageNums = true
    ShowToc = false
  [params.homeInfoParams]
 # enabled = true
  title = "Welcome!"
  content = "My name is Ahmad and I’ve been working in the field of data for the past few years. On this blog, I share my projects, insights, and the fascinating aspects of data science and analytics that inspire me."
 # imageUrl = "profilepic.png"
 # defaultTheme = "auto"
#    [[params.profileMode.buttons]]
#    name = "Blog"
#    url = "posts"
[[params.socialIcons]]
name = "github"
url = "https://github.com/AMohammadzadeh"

[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/ahmad-mohammadzadeh/"

[params.assets]
disableFingerprinting = true


[services]
  [services.googleAnalytics]
    id = 'G-T3FF73RDK5'